# Generated by Django 5.2.4 on 2025-08-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='phone_number')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField(default=False, verbose_name='is_read')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='StoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('image', models.ImageField(upload_to='stores/', verbose_name='image')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('name_en', models.CharField(max_length=128, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=128, null=True, verbose_name='name')),
                ('address', models.CharField(max_length=128, verbose_name='address')),
                ('address_en', models.CharField(max_length=128, null=True, verbose_name='address')),
                ('address_uz', models.CharField(max_length=128, null=True, verbose_name='address')),
                ('phone_number', models.CharField(max_length=13, verbose_name='phone_number')),
                ('working_hours', models.CharField(max_length=255, verbose_name='working_hours')),
                ('working_hours_en', models.CharField(max_length=255, null=True, verbose_name='working_hours')),
                ('working_hours_uz', models.CharField(max_length=255, null=True, verbose_name='working_hours')),
                ('location_link', models.URLField(verbose_name='location_link')),
                ('picked', models.BooleanField(default=False, verbose_name='picked')),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
            },
        ),
    ]
