# Generated by Django 5.2.4 on 2025-07-22 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.basemodel')),
                ('image', models.ImageField(upload_to='stores/')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=13)),
                ('working_hours', models.CharField(max_length=255)),
                ('location_link', models.URLField()),
                ('picked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
            },
            bases=('pages.basemodel',),
        ),
    ]
