# Generated by Django 5.2.4 on 2025-08-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_storemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='address_en',
            field=models.CharField(max_length=128, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='storemodel',
            name='address_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='storemodel',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='storemodel',
            name='name_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='storemodel',
            name='working_hours_en',
            field=models.CharField(max_length=255, null=True, verbose_name='working_hours'),
        ),
        migrations.AddField(
            model_name='storemodel',
            name='working_hours_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='working_hours'),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='is_read'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='address',
            field=models.CharField(max_length=128, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='image',
            field=models.ImageField(upload_to='stores/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='location_link',
            field=models.URLField(verbose_name='location_link'),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='picked',
            field=models.BooleanField(default=False, verbose_name='picked'),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='working_hours',
            field=models.CharField(max_length=255, verbose_name='working_hours'),
        ),
    ]
